apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: togather-dev-infra

requires:
  - configs: ["togather-auth-cfg"]  # includes specific named configs within the file path. If empty, then all configs in the file are included.
    path: ./micro-services/togather-auth-service
  - configs: ["togather-booking-finance-cfg"] 
    path: ./micro-services/togather-booking-finance-service  
  - configs: ["togather-chat-cfg"] 
    path: ./micro-services/togather-chat-service
  - configs: ["togather-experience-cfg"] 
    path: ./micro-services/togather-experience-service
  - configs: ["togather-feed-cfg"] 
    path: ./micro-services/togather-feed-service
  - configs: ["togather-graphql-cfg"] 
    path: ./micro-services/togather-graphql-service 
  - configs: ["togather-location-cfg"] 
    path: ./micro-services/togather-location-service 
  - configs: ["togather-notification-cfg"] 
    path: ./micro-services/togather-notification-service
  - configs: ["togather-partner-cfg"]  
    path: ./micro-services/togather-partner-service
  - configs: ["togather-user-cfg"] 
    path: ./micro-services/togather-user-service
  - configs: ["togather-websocket-cfg"] 
    path: ./micro-services/togather-websocket-service 
  # or reference remote git configs (see docs/tutorial for remote examples)

manifests:
  rawYaml:
    - ./K8s/auto/* # DB, kafka, redis, etc.

# build is handled in each module - we can skip this in the orchestration.
# build:
#   local:
#     useDockerCLI: false # use docker command-line interface instead of Docker Engine APIs.
#     tryImportMissing: false # whether to attempt to import artifacts from Docker (either a local or remote registry) if not in the cache.
#     concurrency: 1 # how many artifacts can be built concurrently. 0 means "no-limit".
#     push: false # should images be pushed to a registry.
#   tagPolicy:
#     gitCommit: {} #beta: tags images with the git tag or commit of the artifact's workspace(context).
#   artifacts:
#     - image: gcr.io/k8s-skaffold/node-example
#       context: ../togather-user-service # where to look for .docker file (local path)
#       docker:
#         dockerfile: Dockerfile.Dev
#       sync:
#         manual:
#           - src: "src/**/*.ts"
#             dest: .

deploy:
  kubectl: {}
