apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: togather-dev-infra

requires:
  - configs: ["togather-user-cfg"]
    path: ../user-service/skaffold.yaml
  - configs: ["togather-auth-cfg"]
    path: ../auth-service/skaffold.yaml
  # or reference remote git configs (see docs/tutorial for remote examples)

manifests:
  rawYaml:
    - k8s/auto/*.yaml # DB, kafka, redis, etc.

build:
  local:
    useDockerCLI: false # use docker command-line interface instead of Docker Engine APIs.
    tryImportMissing: false # whether to attempt to import artifacts from Docker (either a local or remote registry) if not in the cache.
    concurrency: 1 # how many artifacts can be built concurrently. 0 means "no-limit".
    push: false # should images be pushed to a registry.
  tagPolicy:
    gitCommit: {} #beta: tags images with the git tag or commit of the artifact's workspace(context).
  artifacts:
    - image: gcr.io/k8s-skaffold/node-example
      context: ../togather-user-service # where to look for .docker file (local path)
      docker:
        dockerfile: Dockerfile.Dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl: {}
